# 例外処理 その2
## 概要
1. 例外を意図的に発生させる...`throw`
2. 例外をメソッドの呼び出しもとに投げる...`throws`
3. オリジナルの例外...`独自例外`  
   
---

## throw と throws
### throwの利用イメージ
```Java
//例外を発生させ、自分でcatchしている
try{
    if(num > 10){
        throw new Exception("範囲外の値です"); 
    }
} catch(Exception e) {
    System.out.println("例外発生");
}
```

### throwsの利用イメージ
```Java
//メソッドで例外を発生させ・・・
class ClassB{
    public void method(int val) throws Exception{
        if(val > 50){
            throw new Exception("値が異常です");
        }
    }
}
```
```Java
//呼び出しもとでcatchする
public static void main(String[] args){
    try{
        ClassB b = new ClassB();
        b.method(100);
    } catch(Exception e){
        System.out.println("例外発生");
    }
}
```

## 細かい使用方法
### throw
```Java
//発生させてたい例外クラスを記述する
throw new Exception("例外が発生しました");
```

### throws
```Java
//メソッドの後ろに投げたい例外クラスを記述する
public void method(int val) throws Exception{

}
```
この時、非検査例外のRuntimeExceptionは書かなくても自動的にthrowされる。

### ※throwsのoverride
throwsの付いたメソッドをoverrideする場合は、その例外クラスが投げることのできない例外クラスは付与できない。

---

## 独自例外
### 定義の仕方
```Java
class 独自例外のクラス名 extends Exception{
    独自例外のクラス名(String msg){
        super(msg);
    }
}
```